### PR TITLE
Add mediaType to the list of ignored taxonomies

### PR DESCRIPTION
**Pull request by i-like-robots**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
fails tests, but yes +1 — better to hold off until eu referendum stuff is all finished before deploying though

**Comment by matthew-andrews** [comment]
haha, and now tests

**Comment by i-like-robots** [comment]
Maybe I'll try to fix this locally instead of with the Github editor!

**Comment by matthew-andrews** [comment]
😅

**Comment by i-like-robots** [comment]
proper job

**Comment by matthew-andrews** [comment]
+1 für Montag

**Pull request merged**
