### PR TITLE
cleared ALL OF TEH LINTING WARNINGS (º 0º)/º

### PR DESCRIPTION
**Pull request by gvonkoss**
I got carried away and tried to wipe out all of the linting warnings. This is probably going to change when I get around to pushing up the ui branch, so perhaps it's best presented as a suggestion (:

### CODE REVIEW

**Comment by i-like-robots** [comment]
Still merge conflict in there =[

Did you try the `--fix` flag to automagically lint (if it works... it used to be very limited) or go through manually?

**Comment by leggsimon** [comment]
Are you still working on this @gvonkoss ?

**Comment by gvonkoss** [comment]
Not anymore! @leggsimon

**Comment by i-like-robots** [comment]
Closed because this will conflict with every file we've changed in the last 2 weeks and I don't fancy rebasing it!

**Pull request closed without merging**
