### PR TITLE
S3 lifecycle policy

### PR DESCRIPTION
**Pull request by sjparkinson**
Add a lifecycle policy to the Elasticsearch snapshot S3 bucket.

Should help to keep the bucket clean.

Delete objects after 7 days of creation.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html

### CODE REVIEW

**Comment by i-like-robots** [comment]
CC @richard-still-ft @TheoLeanse

**Comment by TheoLeanse** [comment]
👍  coool

**Comment by sjparkinson** [comment]
Mind if I add template validation to the Makefile in another PR?

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-es-interface/pull/569#issuecomment-258162316

pretty sure @TheoLeanse set that up in another project  — maybe time to extract and put into n-makefile?

**Comment by sjparkinson** [comment]
The convention of where people put the templates however could be an issue.

**Comment by TheoLeanse** [comment]
a validation attempt elsewhere for what it's worth: github.com/Financial-Times/next-sitemaps/blob/master/Makefile#L10-L11
template directory and name is just hard coded there

**Pull request merged**
