### PR TITLE
Add asciifolding to our suggestion filter to cater for diacritics

### PR DESCRIPTION
**Pull request by i-like-robots**
https://www.elastic.co/guide/en/elasticsearch/guide/current/asciifolding-token-filter.html

### CODE REVIEW

**Comment by matthew-andrews** [comment]
lóökş ĝō̂od

**Comment by matthew-andrews** [comment]
can we merge this?

**Comment by i-like-robots** [comment]
Yes, but it requires a new index =[

**Comment by matthew-andrews** [comment]
that's ok.  in time.

**Pull request merged**
