### PR TITLE
Revert "Merge pull request #478"

### PR DESCRIPTION
**Pull request by i-like-robots**
Because there are plenty of videos in CAPI that lack descriptions etc.

**We can revert this revert when videos have been reingested to CAPI**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
yawww i think it's becasue thye need to reingest

**Comment by matthew-andrews** [comment]
so we should revert revert when they do that

**Comment by i-like-robots** [comment]
Yes indeed

**Comment by matthew-andrews** [comment]
+1

**Comment by matthew-andrews** [comment]
go go go go gogo

**Pull request merged**
