### PR TITLE
fix: Allow >> in link text for inline links

### PR DESCRIPTION
**Pull request by matthew-andrews**
cc @keirog

### CODE REVIEW

**Comment by keirog** [comment]
👍

**Comment by matthew-andrews** [comment]
this is the offending line: https://github.com/Financial-Times/next-es-interface/blob/master/server/models/article/preresolve-links.js#L5

**Comment by keirog** [comment]
@matthew-andrews ^ Better late than never, I hope

**Comment by matthew-andrews** [comment]
yay cool

**Comment by matthew-andrews** [comment]
make sure we update neil, mus and mark etc !

**Comment by andygnewman** [comment]
I see you've bumped up cheerio 0.22. In other apps we'd not moved from 0.19 to 0.20 because of memory issues it was causing. https://github.com/cheeriojs/cheerio/issues/856

The issue hasn't been closed so not clear if 0.22 resolves the issue or not...

**Comment by keirog** [comment]
Oh thanks @andygnewman, I've knocked it down to 0.19

**Pull request merged**
