### PR TITLE
[DO NOT MERGE] Remove titles and summaries

### PR DESCRIPTION
**Pull request by andygnewman**
Step 4 of https://github.com/Financial-Times/next-es-interface/issues/527

### CODE REVIEW

**Comment by i-like-robots** [comment]
Do you know what needs to be done to be in a position to ship this?

**Comment by andygnewman** [comment]
Yep, all the issues listed here https://github.com/Financial-Times/next-es-interface/issues/527

Will post in #next-elastic channel and continue to fix the ones that I have permissions on.

**Comment by i-like-robots** [comment]
Is it OK to close this branch and drop the titles and summaries when we ship the updated article model?

**Comment by i-like-robots** [comment]
Closing as this is in #690

**Pull request closed without merging**
