### PR TITLE
Add a type for all the models

### PR DESCRIPTION
**Pull request by adgad**
@i-like-robots @TheoLeanse @andygnewman @kavanagh

### CODE REVIEW

**Comment by i-like-robots** [comment]
👍

**Comment by i-like-robots** [comment]
CC @ironsidevsquincy + @andygout does this mean changes are required for Next API?

**Comment by TheoLeanse** [comment]
🕺

**Comment by ironsidevsquincy** [comment]
Yes! Means we can stop doing https://github.com/Financial-Times/next-api/blob/master/server/lib/backends/capi/utils/resolve-content-type.js

**Comment by ironsidevsquincy** [comment]
Well, -ish. Will there be a `liveBlog` type?

**Comment by adgad** [comment]
I think the `type` should be matching the model in ES, so probably will have to leave that `liveBlog` check in Next API (or maybe have an isLiveBlog field or something along those lines in ES?)

**Comment by i-like-robots** [comment]
I reckon leave it to next API as it's just some sugar over `realtime: true` (as per CAPI)

**Pull request merged**
